name       : gedit
version    : 3.28.1
release    : 26
source     :
    - https://download.gnome.org/sources/gedit/3.28/gedit-3.28.1.tar.xz : f174be0958ce63771fef9a81d06da6769358dab8705364a6abb5c7d10ec8211d
license    : GPL-2.0-only
component  : desktop.gnome
summary    : The official text editor of the GNOME desktop
description: |
    While aiming at simplicity and ease of use, gedit is a powerful general purpose text editor.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - itstool
    - vala
rundeps    :
    - python3-gobject
setup      : |
    %configure --disable-static --enable-python --enable-vala
build      : |
    %make
install    : |
    %make_install
