name        : gedit
version     : 3.18.2
release     : 15
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gedit/3.18/gedit-3.18.2.tar.xz : 856e451aec29ee45980011de57cadfe89c3cbc53968f6cc865f8efe0bd0d49b1
license     : GPL-2.0+
summary     : The official text editor of the GNOME desktop
builddeps   :
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python-3.4)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(enchant)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(pygobject-3.0)
    - itstool
rundeps     :
    - python3-gobject
description : |
    While aiming at simplicity and ease of use, gedit is a powerful general purpose text editor.
setup      : |
    %configure --disable-static --enable-python
build      : |
    %make
install    : |
    %make_install
