name       : gedit
version    : 3.20.2
release    : 19
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gedit/3.20/gedit-3.20.2.tar.xz : 32a1276a71a0d4a5af4e20a87bc273170ba8e075fc1ca7f51c8d3a6c150463f8
license    : GPL-2.0+
summary    : The official text editor of the GNOME desktop
component  : desktop.gnome
builddeps  :
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(enchant)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gspell-1)
    - itstool
rundeps    :
    - python3-gobject
description: |
    While aiming at simplicity and ease of use, gedit is a powerful general purpose text editor.
setup      : |
    %configure --disable-static --enable-python
build      : |
    %make
install    : |
    %make_install
