name       : gedit
version    : 41a
release    : 42
source     :
    - https://download.gnome.org/sources/gedit/41/gedit-41.alpha.tar.xz : 4e445d7d2b5c0b088d32cce9dbd17d5507b3362adf6fa985c975282323233f3a
license    : GPL-2.0-only
component  : desktop.gnome
summary    : The official text editor of the GNOME desktop
description: |
    While aiming at simplicity and ease of use, gedit is a powerful general purpose text editor.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gdlib)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - appstream-glib
    - desktop-file-utils
    - gtk-doc
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - python-gobject
setup      : |
    %meson_configure -Ddocumentation=true
build      : |
    %ninja_build
install    : |
    %ninja_install
