name       : gedit
version    : 3.22.1
release    : 22
source     :
    - https://ftp.gnome.org/pub/gnome/sources/gedit/3.22/gedit-3.22.1.tar.xz : aa7bc3618fffa92fdb7daf2f57152e1eb7962e68561a9c92813d7bbb7fc9492b
license    : GPL-2.0+
summary    : The official text editor of the GNOME desktop
component  : desktop.gnome
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - itstool
rundeps    :
    - python3-gobject
description: |
    While aiming at simplicity and ease of use, gedit is a powerful general purpose text editor.
setup      : |
    %configure --disable-static --enable-python
build      : |
    %make
install    : |
    %make_install
