name       : gedit
version    : 3.38.1
release    : 37
source     :
    - https://download.gnome.org/sources/gedit/3.38/gedit-3.38.1.tar.xz : 0053853d2cd59cad8a1662f5b4fdcfab47b4c0940063bacd6790a9948642844d
license    : GPL-2.0-only
component  : desktop.gnome
summary    : The official text editor of the GNOME desktop
description: |
    While aiming at simplicity and ease of use, gedit is a powerful general purpose text editor.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gdlib)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(tepl-5)
    - appstream-glib
    - desktop-file-utils
    - gtk-doc
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - python-gobject
setup      : |
    %meson_configure -Ddocumentation=true
build      : |
    %ninja_build
install    : |
    %ninja_install
