name       : gedit
version    : 3.32.2
release    : 28
source     :
    - https://download.gnome.org/sources/gedit/3.32/gedit-3.32.2.tar.xz : 742fef5e496f5d0dbc95dac5c5547f040dffbea55cd835e6618294eadd9959e0
license    : GPL-2.0-only
component  : desktop.gnome
summary    : The official text editor of the GNOME desktop
description: |
    While aiming at simplicity and ease of use, gedit is a powerful general purpose text editor.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gdlib)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - appstream-glib
    - desktop-file-utils
    - gtk-doc
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - python3-gobject
setup      : |
    %meson_configure -Ddocumentation=true
build      : |
    %ninja_build
install    : |
    %ninja_install
