name       : gedit
version    : '43.2'
release    : 50
source     :
    - https://download.gnome.org/sources/gedit/43/gedit-43.2.tar.xz : f950d2d35c594bb6c8dbc9f5440cad7788ca0a8688e2b07846f83de9a4e3fc25
homepage   : https://gitlab.gnome.org/GNOME/gedit/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : The official text editor of the GNOME desktop
description: |
    While aiming at simplicity and ease of use, gedit is a powerful general purpose text editor.
builddeps  :
    - pkgconfig(gdlib)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(tepl-6)
    - appstream-glib
    - desktop-file-utils
    - gtk-doc
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - python-gobject
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
