name       : gedit
version    : 3.22.0
release    : 21
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gedit/3.22/gedit-3.22.0.tar.xz : 063b5a0b5dcc8f540f6e8c3ea1c22cf8a3a19edffc25315a1b6bc51d462b3f45
license    : GPL-2.0+
summary    : The official text editor of the GNOME desktop
component  : desktop.gnome
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - itstool
rundeps    :
    - python3-gobject
description: |
    While aiming at simplicity and ease of use, gedit is a powerful general purpose text editor.
setup      : |
    %configure --disable-static --enable-python
build      : |
    %make
install    : |
    %make_install
